class TestLocators:
    loc_open_dresses = '/html/body/div[1]/div/nav/div[2]/ul/li[4]/a'
    loc_open_dress = '/html/body/div[2]/div[2]/div/div[3]/div[1]/div/div[1]/a/img[2]'
    loc_add_to_cart = '/html/body/div[2]/div[2]/div/div[1]/div[2]/div[3]/div[4]/button'
    loc_go_to_cart = '/html/body/div[4]/div/div/div[2]/div[3]/a[1]/strong/span'
    loc_making_order = '/html/body/div[2]/div/div/div[3]/div[2]/a'
    loc_my_name = '/html/body/div[2]/div/div/div[1]/div/div/div[1]/div[2]/div[2]/fieldset/div[1]/div/input'
    loc_my_mobile = '/html/body/div[2]/div/div/div[1]/div/div/div[1]/div[2]/div[2]/fieldset/div[2]/div/input'
    loc_my_town = '/html/body/div[2]/div/div/div[1]/div/div/div[1]/div[3]/div[2]/fieldset/div[1]/div/input'
    loc_comment = '/html/body/div[2]/div/div/div[1]/div/div/div[1]/div[5]/div[2]/textarea'
    loc_order_confirmation = '/html/body/div[2]/div/div/div[1]/div/div/div[5]/div[1]/a/span'